Flow path issue
Hi, thanks for this repo. 

When I add @flow to any component I get lots of 'Required module not found' 

```
Error: app/scripts/containers/App.jsx:14
 14: import { showAlert } from 'actions';
                               ^^^^^^^^^ actions. Required module not found
``` 

So this update solve this issue